### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by h4ckl4bm3** [nitrotm/virtualbox-php#1]
Hello, thank you for your work... Can you please let me know about installation process? I am trying to do it, but I can not :/

(maybe some step-by-step? ) thanks again...

**Comment by nitrotm** [comment]
Hello, thanks for the interest.
I'll add instructions in the readme shortly.
In the meantime, it's pretty basic:
1) compile vboxxml binary (using gnu make)
2) install it along the virtualbox binaries (by default into /usr/lib/virtualbox)
3) copy the php files where your webserver serve files and edit include/config.inc.php to reflect your setup parameters

**Comment by nitrotm** [comment]
Are you planning to run it on linux?

**Comment by h4ckl4bm3** [comment]
Hello Nitrotm... 

Woww ! Thank you very much for answering me ... I really can not believe you're doing it, thanks again ... I've been trying to install on Linux (osboxes @ osboxes: ~ $ cat / proc / version
Linux version 4.10.0-38-generic (buildd @ lgw01-amd64-032) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2)) # 42-Ubuntu SMP Tue Oct 10 13:24:27 UTC 2017
) but I have not succeeded so far ... Any special distro?
Always see the same error.
osboxes@osboxes:~/virtualbox-php/vboxxml$ ls
docs  include  Makefile  run.sh  vboxxml
osboxes@osboxes:~/virtualbox-php/vboxxml$ make
compiling...
 vboxxml/machine.cpp
In file included from include/vboxxml.h:7:0,
                 from vboxxml/machine.cpp:2:
include/vbox.h:26:22: fatal error: nsMemory.h: No such file or directory
 #include <nsMemory.h>
                      ^
compilation terminated.
Makefile:49: recipe for target 'vboxxml/machine.o' failed
make: *** [vboxxml/machine.o] Error 1

I've been trying to install a lot of libraries (searching some similar error on google) but not succeeded yet :/

Any suggestion please... Thanks again for your time :) Best regards from Colombia

**Comment by nitrotm** [comment]
Alright, no problem.

I think it's because the Makefile is configured to look for virtualbox's installation files in /usr/lib/virtualbox by default. Also, it expects the virtualbox sdk to be installed in /usr/lib/virtualbox/sdk/bindings/xpcom.

You can override these variables when you run make (for instance if you installed in /opt/virtualbox):
`make VBOX_PATH=/opt/virtualbox`.

You might also set where you unpacked the official sdk like so:
`make VBOX_PATH=/opt/virtualbox XPCOM_PATH=~/Downloads/VirtualboxSDK/bindings/xpcom`.

The sdk can be found there (VirtualBox x.x.x Software Developer Kit (SDK) -> All platforms):
https://www.virtualbox.org/wiki/Downloads

**Comment by h4ckl4bm3** [comment]
Thanks my friend... Again :)

I do it with some modifications (for my system)

compiling...
 vboxxml/machine.cpp
 vboxxml/medium.cpp
 vboxxml/system.cpp
 vboxxml/main.cpp
linking...
vboxxml/machine.o: In function `exportVirtualBoxBIOSSettings(IBIOSSettings*, _xmlTextWriter*)':
/home/osboxes/virtualbox-php/vboxxml/vboxxml/machine.cpp:372: undefined reference to `xmlTextWriterStartElement'
/home/osboxes/virtualbox-php/vboxxml/vboxxml/machine.cpp:372: undefined reference to `xmlTextWriterWriteAttribute'
/home/osboxes/virtualbox-php/vboxxml/vboxxml/machine.cpp:372: undefined reference to `xmlTextWriterWriteString'
/home/osboxes/virtualbox-php/vboxxml/vboxxml/machine.cpp:372: undefined reference to `xmlTextWriterEndElement'

...............................
follow
collect2: error: ld returned 1 exit status
Makefile:42: recipe for target 'VBoxXML' failed
make: *** [VBoxXML] Error 1

Too close :P (I copy all downloaded sdk to /usr/lib/virtualbox/sdk/ ) and run
# make VBOX_PATH=/usr/lib/virtualbox/ XPCOM_PATH=/usr/lib/virtualbox/sdk/bindings/xpcom/

Thanks again... I will do some searches... Please let me know if you have another hint

**Comment by nitrotm** [comment]
Do you have libxml2-dev installed?

**Comment by h4ckl4bm3** [comment]
Yes, the same error :/
I am doing a new debian installation for try it again... Sorry for your time :/
(Collect2: error: ld returned 1 exit status
Makefile:42: recipe for target 'VBoxXML' fail)

**Comment by nitrotm** [comment]
I tested on debian 8.9 (which provides Virtualbox 4.3) and it compiles okay for me. If you have virtualbox <5.1, you have to checkout the corresponding git tag (4.3 or 5.0). Otherwise the master branch is fine from 5.1 onward.

If you have an old virtualbox version, you have to install the correct sdk:
https://www.virtualbox.org/wiki/Download_Old_Builds

Also I had to install (and the sdk version 4.3 manually):
`apt get install git build-essential libxml2-dev virtualbox`

And then run:
`make XPCOM_PATH=/home/virtualbox/sdk/bindings/xpcom/ clean all`

**Comment by nitrotm** [comment]
Okay, so I added the doc/readme and verified that it's possible to build under Debian >= 8. I am closing this topic. Feel free to open a new one if you have another issue.
